[env:seeed_xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino

; OPI PSRAM (XIAO ESP32-S3 Sense)
board_build.arduino.memory_type = qio_opi

build_flags =
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_CDC_ON_BOOT=1

lib_deps =
    bblanchon/ArduinoJson@^7.0.0
    Links2004/WebSockets@^2.4.0

monitor_speed = 115200
upload_port   = /dev/cu.usbmodem14301
monitor_port  = /dev/cu.usbmodem14301
